Fix: ImportError: cannot import name 'main' from 'bot' (unknown location)
Since main.py renamed to __main__, so i change the import code from 'main' to '__main__'

Signed-off-by: Aziz Ridhwan <fwindows345@gmail.com>